version: '3.8'

services:
  jobdone-metric-importer:
    build: 
      context: .
      no_cache: true
    environment:
      - NODE_ENV=production
    command: bun run start
    volumes:
      - ./logs/jobdone-metric-importer:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
