import type { AppConfig, HelloTESSSourceConfig } from "../config";
import { getEnvVar } from "../config";

export const appConfigKusch: AppConfig = {
  sources: [
    {
      name: "revenue-actual-seehaus",
      type: "hellotess",
      enabled: true,
      ignoredMissingCostCenters: [],
      autoCreateMetricType: false,
      metricTypeCategory: "Ist",
      mergeMetricTypes: {
        enabled: true,
        name: "Umsatz",
      },
      metricTypeMappings: [],
      costCenterMappingField: "customId3",
      apiKey: getEnvVar("HELLOTESS_SEEHAUS_API_KEY", true),
      host: getEnvVar("HELLOTESS_SEEHAUS_HOST", true),
      daysPast: 7,
      daysFuture: 0,
      storeId: getEnvVar("HELLOTESS_SEEHAUS_STORE_ID", true),
      costCenterFrom: "storeId",
      revenueType: "net",
      historicalImport: {
        enabled: true,
        startDate: "2025-01-01",
        batchSizeInDays: 10,
      },
    } as HelloTESSSourceConfig,
    {
      name: "revenue-actual-chamanna",
      type: "hellotess",
      enabled: true,
      ignoredMissingCostCenters: [],
      autoCreateMetricType: false,
      metricTypeCategory: "Ist",
      mergeMetricTypes: {
        enabled: true,
        name: "Umsatz",
      },
      metricTypeMappings: [],
      costCenterMappingField: "customId3",
      apiKey: getEnvVar("HELLOTESS_CHAMANNA_API_KEY", true),
      host: getEnvVar("HELLOTESS_CHAMANNA_HOST", true),
      daysPast: 7,
      daysFuture: 0,
      storeId: getEnvVar("HELLOTESS_CHAMANNA_STORE_ID", true),
      costCenterFrom: "storeId",
      storeNameFilter: "Chamanna",
      revenueType: "net",
      historicalImport: {
        enabled: true,
        startDate: "2025-01-01",
        batchSizeInDays: 10,
      },
    } as HelloTESSSourceConfig,
    {
      name: "revenue-actual-la-baracca",
      type: "hellotess",
      enabled: true,
      ignoredMissingCostCenters: [],
      autoCreateMetricType: false,
      metricTypeCategory: "Ist",
      mergeMetricTypes: {
        enabled: true,
        name: "Umsatz",
      },
      metricTypeMappings: [],
      costCenterMappingField: "customId3",
      apiKey: getEnvVar("HELLOTESS_LA_BARACCA_API_KEY", true),
      host: getEnvVar("HELLOTESS_LA_BARACCA_HOST", true),
      daysPast: 7,
      daysFuture: 0,
      storeId: getEnvVar("HELLOTESS_LA_BARACCA_STORE_ID", true),
      costCenterFrom: "storeId",
      storeNameFilter: "la baracca",
      revenueType: "net",
      historicalImport: {
        enabled: true,
        startDate: "2025-01-01",
        batchSizeInDays: 10,
      },
    } as HelloTESSSourceConfig,
  ],
  diskFreeSpaceThresholdInPercent: 20,
  timeZone: "Europe/Zurich",
};
